baseURL = "https://busayo.xyz/"
languageCode = "en-us"
title = "test"
theme = "aether"

[params]
brand = "test"
description = "Design, code and words"
homeimg = "https://res.cloudinary.com/busayyyo/image/upload/v1570483412/blog/green-pattern-surface-131683.jpg"
bgimg = "https://res.cloudinary.com/busayyyo/image/upload/v1570483607/blog/art-background-close-up-1939485.jpg"
rssinmenu = true

//changes does not affect page
