baseURL = "https://busayo.xyz/"
languageCode = "en-us"
title = "Busayo Oyewole - Design, Code and Words"
theme = "aether"
brand = "Busayo Oyewole"
description = "Design, code and words"
homeimg = "https://res.cloudinary.com/busayyyo/image/upload/v1570480123/blog/blog_logo.svg"
bgimg = "https://res.cloudinary.com/busayyyo/image/upload/v1570480750/blog/background-3246124_1920.jpg"
rssinmenu = true
