baseurl = "https://busayo.xyz/"
languageCode = "en-us"
title = "Design, Code and Words"
author = "Busayo Oyewole"
canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = "Busayo Oyewole"
description = "Design, code and words"
homeimg = "https://res.cloudinary.com/busayyyo/image/upload/v1570482362/blog/background-border-bright-630754.jpg"
bgimg = "https://res.cloudinary.com/busayyyo/image/upload/v1570482484/blog/astro-astronomy-background-956999.jpg"
rssinmenu = true
