baseurl = "https://busayo.xyz/"
languageCode = "en-us"
title = "Busayo"
author = "Busayo Oyewole"
canonifyurls = true
paginate = 5
theme = "aether"

[params]
brand = "Busayo Oyewole"
description = "In pursuit of self and knowledge"
homeimg = "https://res.cloudinary.com/busayyyo/image/upload/v1571083557/blog/christmas-1911637_1920.jpg"
bgimg = "https://res.cloudinary.com/busayyyo/image/upload/v1570484496/blog/blog_bg.png"
rssinmenu = false
